"$schema" = 'https://starship.rs/config-schema.json'
format = """
[╭ ](white)$directory$git_branch$git_commit$rust$time$cmd_duration
[╰─](white)$character
"""

[time]
disabled = false
format = '[$time]($style) '
time_format = '%F %T'

[directory]
truncate_to_repo = false
[directory.substitutions]
'//home/jak' = '~' # homedir should be replaced by ~ automatically... but it's not for some reason?

[git_branch]
ignore_branches = ['master', 'main']
format = '[$symbol$branch(:$remote_branch)]($style) '
symbol = ''

[rust]
format = '[$symbol($version )]($style)'
version_format = '${raw}'
symbol = '🦀'

