theme = "ferra"

[editor]
mouse = false
rulers = [80]

[editor.file-picker]
hidden = false

[editor.cursor-shape]
insert = "bar"
select = "underline"

[editor.indent-guides]
render = true

[editor.soft-wrap]
enable = true

[editor.lsp]
display-messages = true
display-progress-messages = true

[editor.whitespace.render]
space = "all"
tab = "all"
nbsp = "all"
nnbsp = "all"
newline = "none"

[editor.inline-diagnostics]
cursor-line = "warning"
other-lines = "error"
